/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.Encomienda;
import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class Encomiendas extends javax.swing.JFrame {
    
    Calendar horas = new GregorianCalendar();
    
    ArrayList<Encomienda> listaEncomienda = new ArrayList();

    /**
     * Creates new form Encomiendas
     */
    public Encomiendas() {
        initComponents();
        hora.setCalendar(horas);
        
        //conexion a la base de datos
        Conexion msql = new Conexion();
        msql.conectar();
        
        //crear una lista para llenar el combo Box de Bus
        ArrayList<String> lista = new ArrayList<String>();
        
        //Se ejecuta el metodo de la base de datos y se pasa a la variable lista del ARRAYLIST
        lista = msql.llenar_combo_Bus();
        
        //llanado de lista 
        for (int i = 0; i < lista.size(); i++) {
          BusCbx.addItem(lista.get(i));  
        }
        
        //Se crea una lista para llenar el combo box de Viajes
         ArrayList<String> lista1 = new ArrayList<String>();
         //llenar la lista ejecutando lo que hay en la base de datos
         lista1 = msql.llenar_combo_Viajes();
         //llenado de lista mediante un for 
         for (int i = 0; i < lista1.size(); i++) {
            viajarCbx.addItem(lista1.get(i));
        }
      
    }
    
    public void cargarDatos(ArrayList<Encomienda> listaEncomienda){
        this.listaEncomienda = listaEncomienda;
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        hora = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        pesotxt = new javax.swing.JTextField();
        fechLlegadatxt = new com.toedter.calendar.JDateChooser();
        fechSalidatxt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pxptxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nretiratxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BusCbx = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        salidatxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        destinotxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        viajarCbx = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        EstadoCbx = new javax.swing.JComboBox<>();
        BtnRegresar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Envío Encomiendas");
        setMinimumSize(new java.awt.Dimension(768, 486));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Envío Encomiendas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 170, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Salida:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 90, 30));

        BtnAgregar.setBackground(new java.awt.Color(0, 51, 51));
        BtnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(0, 255, 0));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 40, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Código Encomienda:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 30));
        getContentPane().add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 210, 30));

        hora.setDateFormatString("HH:mm:ss");
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 230, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese el Peso:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, 30));
        getContentPane().add(pesotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 170, 30));
        getContentPane().add(fechLlegadatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 230, 30));
        getContentPane().add(fechSalidatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 250, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Persona Entrega Encomienda:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 30));
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 210, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio x Peso:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, 30));
        getContentPane().add(pxptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 99, 170, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre Persona Retira Encomienda:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 30));
        getContentPane().add(nretiratxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Viaje:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 40, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número de Bus:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 100, 30));

        BusCbx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(BusCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 220, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lugar de Salida:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 30));
        getContentPane().add(salidatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lugar de Destino:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 30));
        getContentPane().add(destinotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 250, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha Llegada:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 90, 30));

        getContentPane().add(viajarCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 220, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estado Encomienda:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 30));

        EstadoCbx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EstadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En espera de salida", "En viaje", "Pendiente de retiro", "Retirado" }));
        getContentPane().add(EstadoCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 180, 30));

        BtnRegresar.setBackground(new java.awt.Color(51, 0, 0));
        BtnRegresar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 0, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 90, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/evios.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        //Se utiliza para obtener las fechas según el formatod de la base de datos
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fe = sdf.format(fechSalidatxt.getDate());
        String fsalida = sdf.format(fechSalidatxt.getDate());
        String fllegada = sdf.format(fechLlegadatxt.getDate());
        
        //Conexion con la base de datos Mysql
        Conexion msql = new Conexion();
        Connection conexion = msql.conectar();
        String sSql="";
        
        //variables String 
        String code,peso,pxp,name,nretira,salida,destino,Fecha_Entrega_Destinario,Hora_Entrega_Destinario,viaje,bus;
        
        code = codigotxt.getText();
        peso= pesotxt.getText();
        pxp = pxptxt.getText();
        name = nametxt.getText();
        nretira = nretiratxt.getText();
        salida = salidatxt.getText();
        destino = destinotxt.getText();
        Fecha_Entrega_Destinario = "";
        Hora_Entrega_Destinario = "";

        //agarar texto de Combo box y convertir a String 
        bus = (String) BusCbx.getSelectedItem();
        viaje = (String) viajarCbx.getSelectedItem();
      
        //System.out.println(""+viaje);
       String estados = (String) EstadoCbx.getSelectedItem();
       
       //Convertir de String a Int para array de controlador
        int bus1 = Integer.parseInt(bus);
      
        
        //Capturar Valores de Horas y convertirlas a String
       String hs = String.valueOf(hora.getDate());
       //Consulta de Insert a la base de datos
        sSql ="INSERT INTO `encomienda`(`Id_Encomienda`, `Codigo`, `Peso`, `Precio_X_Peso`, `Nombre_Persona_Entrega`, `Nombre_Persona_Retira`, `Viajes`, `Id_Flotilla`, `Lugar_Salida`, `Lugar_Destino`, `hora`, `FechaSalida`, `FechaLlegada`, `Fecha_Entrega_Destinario`, `Hora_Entrega_Destinario`, `Estado`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try{
           PreparedStatement pst = (PreparedStatement) conexion.clientPrepareStatement(sSql);
           pst.setString(1, null);
           pst.setString(2, code);
           pst.setString(3, peso);
           pst.setString(4, pxp);
           pst.setString(5, name);
           pst.setString(6, nretira);
           pst.setString(7, viaje);
           pst.setString(8, bus);
           pst.setString(9, salida);
           pst.setString(10,destino);
           pst.setString(11,((JTextField)hora.getDateEditor().getUiComponent()).getText());
           pst.setString(12,fsalida);
           pst.setString(13,fllegada);
           pst.setString(14,Fecha_Entrega_Destinario);
           pst.setString(15,Hora_Entrega_Destinario);
           pst.setString(16,estados);

           int n = pst.executeUpdate();
            if(n > 0){
                JOptionPane.showMessageDialog(null,"El registro se ha Ingresado","Base de Datos MySql",JOptionPane.INFORMATION_MESSAGE);
            }
                
        }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error::"+e,"Ingreso MySql",JOptionPane.ERROR);
           
        }
        
       
        Encomienda enco = new Encomienda(code,peso,pxp,name,nretira,viaje,bus1,salida,destino,hs,fsalida,fllegada,Fecha_Entrega_Destinario,Hora_Entrega_Destinario,estados);
        listaEncomienda.add(enco);
        codigotxt.setText("");
        pesotxt.setText("");
        pxptxt.setText("");
        nametxt.setText("");
        nretiratxt.setText("");
        salidatxt.setText("");
        destinotxt.setText("");
        hora.setDate(null);
        fechSalidatxt.setDate(null);
        fechLlegadatxt.setDate(null);
        codigotxt.requestFocus();
         JOptionPane.showMessageDialog(null, "Registrado con exito!", "Respuesta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    
    public ArrayList<Encomienda> nuevo() {
         return listaEncomienda;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encomiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encomiendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> BusCbx;
    private javax.swing.JComboBox<String> EstadoCbx;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JTextField destinotxt;
    private com.toedter.calendar.JDateChooser fechLlegadatxt;
    private com.toedter.calendar.JDateChooser fechSalidatxt;
    private com.toedter.calendar.JDateChooser hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nretiratxt;
    private javax.swing.JTextField pesotxt;
    private javax.swing.JTextField pxptxt;
    private javax.swing.JTextField salidatxt;
    private javax.swing.JComboBox<String> viajarCbx;
    // End of variables declaration//GEN-END:variables
}
