/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class RetiroEncomienda extends javax.swing.JFrame {

    /**
     * Creates new form RetiroEncomienda
     */
    public RetiroEncomienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        times = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        estadoCbx = new javax.swing.JComboBox<>();
        BtnAgregar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retiro de Encomienda");
        setMaximumSize(new java.awt.Dimension(501, 380));
        setMinimumSize(new java.awt.Dimension(501, 380));
        setPreferredSize(new java.awt.Dimension(501, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Retiro de Encomienda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 180, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Digite Código de Encomienda:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 30));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 200, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Fecha Entrega Destinario :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 30));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Hora Entrega Destinario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 30));

        times.setDateFormatString("HH:mm:ss");
        getContentPane().add(times, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, 30));

        estadoCbx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        estadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En espera de salida", "En viaje", "Pendiente de retiro", "Retirado" }));
        getContentPane().add(estadoCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 30));

        BtnAgregar.setBackground(new java.awt.Color(51, 255, 51));
        BtnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(0, 102, 0));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, 30));

        BtnRegresar.setBackground(new java.awt.Color(51, 0, 0));
        BtnRegresar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnRegresar.setForeground(new java.awt.Color(255, 0, 0));
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retiro.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
         //Se utiliza para obtener las fechas según el formatod de la base de datos
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fe = sdf.format(fecha.getDate());  
        
         //Conexion con la base de datos Mysql
        Conexion msql = new Conexion();
        Connection conexion = msql.conectar();
       
        
        String code,estado;
        code = codigo.getText();
        
        //agarar texto de Combo box y convertir a String 
        estado = (String) estadoCbx.getSelectedItem();
        
        //Consulta de Insert a la base de datos
         String sSql="UPDATE `encomienda` SET `Fecha_Entrega_Destinario`='"+fe+"',`Hora_Entrega_Destinario`='"+((JTextField)times.getDateEditor().getUiComponent()).getText()+"',`Estado`='"+estado+"'WHERE `Codigo`='"+code+"'";
        try{
            PreparedStatement pst = (PreparedStatement) conexion.clientPrepareStatement(sSql);
            int n = pst.executeUpdate(sSql);
            if(n > 0){
                JOptionPane.showMessageDialog(null,"El registro se ha Ingresado","Base de Datos MySql",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error::"+e,"Ingreso MySql",JOptionPane.ERROR);
        }
     
        
        
    }//GEN-LAST:event_BtnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetiroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetiroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetiroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetiroEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetiroEncomienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> estadoCbx;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser times;
    // End of variables declaration//GEN-END:variables
}
