/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.precio;
import Controlador.viaje;
import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class Viajes extends javax.swing.JFrame {
    
    ArrayList<viaje> listaViaje = new ArrayList();
    ArrayList<precio> listaPrecio = new ArrayList();

    /**
     * Creates new form Viajes
     */
    public Viajes() {
        initComponents();
        //llamado a Modelo 
        Conexion msql = new Conexion();
        
        //llamar el metodo conectar de modelo
        msql.conectar();
        
        
        ArrayList<String> lista = new ArrayList<String>();
        //pasamos la lista creada en modelo el metodo llenar_combo que es una lista lo pasamos a otra
        lista = msql.llenar_combo_Bus();
        
        for (int i = 0; i < lista.size(); i++) {
          BusCbx.addItem(lista.get(i));  
        }
        
        
        ArrayList<String> lista1 = new ArrayList<String>();
        lista1 = msql.llenar_combo_Precios();
         for (int i = 0; i < lista1.size(); i++) {
          PrecioCbx.addItem(lista1.get(i));  
        }
    }
    
    public void cargarDatos(ArrayList<viaje> listaViaje){
        this.listaViaje = listaViaje;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Salidatxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        llegadatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PrecioCbx = new javax.swing.JComboBox<>();
        hllegadatxt = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        kilometrostxt = new javax.swing.JTextField();
        hsalidatxt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        BusCbx = new javax.swing.JComboBox<>();
        dates = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar Viajes");
        setMinimumSize(new java.awt.Dimension(522, 574));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Ingresar Viajes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Digite el Lugar de Salida:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 30));
        getContentPane().add(Salidatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 210, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Digite Lugar de Llegada:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 30));
        getContentPane().add(llegadatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 210, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Seleccionar Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 30));

        PrecioCbx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(PrecioCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, 30));

        hllegadatxt.setDateFormatString("HH:mm:ss");
        getContentPane().add(hllegadatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 420, 200, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Digite Cantidad de kilometros:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 30));

        kilometrostxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kilometrostxtKeyTyped(evt);
            }
        });
        getContentPane().add(kilometrostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 30));

        hsalidatxt.setDateFormatString("HH:mm:ss");
        getContentPane().add(hsalidatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 210, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Bus Número:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 90, 30));

        BusCbx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(BusCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 210, 30));
        getContentPane().add(dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 210, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Hora Salida:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 80, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Hora Llegada:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 80, 30));

        BtnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 90, 30));

        BtnRegresar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 100, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/viaj.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 720, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kilometrostxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kilometrostxtKeyTyped
         //validar para que solo se pueda ingresar numeros
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingresar Solo Números");
        }
    }//GEN-LAST:event_kilometrostxtKeyTyped

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
       //Conexión a la base de datos
        Conexion msql = new Conexion();
        Connection conexion = msql.conectar();
        
        // variable para la base de datos según lo que se ejecute 
        String sSql="";
        
        //formato de la Fecha
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fe = sdf.format(dates.getDate());
        
        //VARIBALES PARA pasar la información 
        String psalida,pllegada,pre,kilometros,bus,convertir,hs,hg,viaje;
        int bus1;
        psalida = Salidatxt.getText();
        pllegada = llegadatxt.getText();
        kilometros = kilometrostxt.getText();
        viaje = psalida+"-"+pllegada;
         
        //agarar texto de Combo box y convertir a String 
        pre = (String) PrecioCbx.getSelectedItem();
        bus = (String) BusCbx.getSelectedItem();

       //convertir de String a Int a Bus ya que en la Base de datos en es Entero
        bus1 = Integer.parseInt(bus);

        //Capturar Valores de Horas y convertirlas a String
        hs = String.valueOf(hsalidatxt.getDate());
        //
        hg =String.valueOf(hllegadatxt.getDate());
        
        //Setencia a Ejecutar en la Base de datos
        sSql ="INSERT INTO `viajes`(`ID_Viajes`, `Punto_salida`, `Punto_destino`, `Precio`, `Cantidad_kilometros`, `Id_flotilla`, `Fecha`, `Hora_salida`, `Hora_llegada`, `viaje`) VALUES (?,?,?,?,?,?,?,?,?,?)";
        
        try{
           PreparedStatement pst = (PreparedStatement) conexion.clientPrepareStatement(sSql);
           pst.setString(1, null);
           pst.setString(2, psalida);
           pst.setString(3, pllegada);
           pst.setString(4, pre);
           pst.setString(5, kilometros);
           pst.setString(6, bus);
           pst.setString(7, fe);
           pst.setString(8,((JTextField)hsalidatxt.getDateEditor().getUiComponent()).getText());
           pst.setString(9,((JTextField)hllegadatxt.getDateEditor().getUiComponent()).getText());
           pst.setString(10, viaje);
           
           int n = pst.executeUpdate();
            if(n > 0){
                JOptionPane.showMessageDialog(null,"El registro se ha Ingresado","Base de Datos MySql",JOptionPane.INFORMATION_MESSAGE);
            }
                
        }catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error::"+e,"Ingreso MySql",JOptionPane.ERROR);
           
        }
        viaje via = new viaje(psalida,pllegada,pre,kilometros,bus1,fe,hs,hg);
        listaViaje.add(via);
        Salidatxt.setText("");
        llegadatxt.setText("");
        kilometrostxt.setText("");
        dates.setCalendar(null);
        hsalidatxt.setCalendar(null);
        hllegadatxt.setCalendar(null);
        Salidatxt.requestFocus();
        JOptionPane.showMessageDialog(null, "Registrado con exito!", "Respuesta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnAgregarActionPerformed

    public ArrayList<viaje> nuevo() {
         return listaViaje;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> BusCbx;
    private javax.swing.JComboBox<String> PrecioCbx;
    private javax.swing.JTextField Salidatxt;
    private com.toedter.calendar.JDateChooser dates;
    private com.toedter.calendar.JDateChooser hllegadatxt;
    private com.toedter.calendar.JDateChooser hsalidatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kilometrostxt;
    private javax.swing.JTextField llegadatxt;
    // End of variables declaration//GEN-END:variables
}
